#!/usr/bin/env bash
tempfile="$(mktemp)"
trap 'rm -rf "${tempfile}"' EXIT
cat > "${tempfile}"

cat "${tempfile}"
if ! [[ $(tail -c1 "${tempfile}" | wc -l) -gt 0 ]]; then
  echo ""
fi

set -- 'source ~/.local/share/yazi/y' 'export EDITOR="hx"' 'eval "$(zoxide init zsh)"' 'alias hux="uv run hx"' 'alias ipytest="uv run --with \"ipdb>0.13\" --with \"ipython>=9.1\" python -m pytest --pdbcls=\"IPython.terminal.debugger:TerminalPdb\""' 'source ~/.local/share/completions/hx.zsh' 'eval "$(~/.local/bin/mise activate zsh)"' 'alias eza="eza --icons --git  --header -L 2  --group-directories-first -s accessed"' 'alias zj="zellij"'
for S in "$@" ; do
  if ! grep -Fxq "$S" "${tempfile}"; then
    echo "$S"
  fi
done
