[tools]
"aqua:fish-shell/fish-shell" = "4.3.3"
bat = "latest"
bibtex-tidy = "1.14.0"
"cargo:fd-find" = "10.3.0"
"cargo:fend" = "1.5.7"
"cargo:https://github.com/Myriad-Dreamin/tinymist" = { version = "tag:v0.14.20", locked = true, crate = "tinymist-cli" }
"cargo:presenterm" = "latest"
duckdb = "1.5.4"
eza = "latest"
fzf = "0.67.0"
"github:fastfetch-cli/fastfetch" = "latest"
helix = "25.07.1"
just = "1.46.0"
node = "25.6.0"
"pipx:gogo-gadget" = "latest"
"pipx:pyright" = "1.1.380"
ripgrep = "latest"
ruff = "0.11.6"
rust = "1.93.0"
starship = "1.24.2"
taplo = "0.10.0"
typst = "0.15.0"
typstyle = "0.14.4"
uv = "0.8.15"
vale = "3.13.1"
yazi = "25.5.31"
zellij = "0.43.1"
zoxide = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
