[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", ".git", ".jj", ".venv/"]
language-servers = ["pyright", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }
language-servers = ["rust-analyzer"]

[[language]]
name = "typst"
language-servers = ["tinymist"]
formatter = { command = "typstyle" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-o","reorder_keys=true", "-"] }
auto-format = false

[[language]]
name = "bibtex"

[language.formatter]
command = "bibtex-tidy"
args = [
  "-",
  "--curly",
  "--remove-empty-fields",
  "--sort-fields",
  "--sort=year,author,id",
  "--trailing-commas",
  "--tidy-comments",
  "--no-escape"
]

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.tinymist]
command = "tinymist"

[language-server.rust-analyzer.config]
check.command = "clippy"
